### ISSUE TITLE
Continuous build

### ISSUE THREAD

**Issue by squaregoldfish** [quince-science/QuinCe#651]
Need to be able to checkout, build and deploy to a test server as an automatic step.

Include Javadoc too.
And JUnit tests, when we've written some.

**Comment by jonasfh** [comment]
Suggested process for release (Might be a single script):

Make new release number (https://semver.org/)

**Lun locally:**
- Rebase the release onto master
- Make a git tag for the release
- Git tag whateverversion 
- Update a changelog.md with changes for this release
- Update version number in build-gradle with the new version number
- Push to the main repository on github

**On production server:**
- Pull latest changes from master branch on main repository
- .gradlew release 
... which does the following: 
    - Build Javadocs
    - Run unit tests
    - Run war - task (with dependencies)
    - Run pre-relase - task, scripts in script/prod/pre-release (where name between version.txt and current version)
    - Run flywayMigrate task, does db migration. Migration files should use version number
    - Run post_release taks, similar to pre-release 
    - Print new version number to version.txt
    - Apply prod configuration: setup_reverse_strings, then  setup_replace_strings.sh
    - Copy task to copy war to tomcat deploy folder
    - Release is aborted if any of the tasks fail!
    - Tomcat automatically reloads new war?!

**Comment by squaregoldfish** [comment]
This will probably come in with moving the test server to a Docker framework once the Carbon Portal has figured out how to do it.

**Comment by squaregoldfish** [comment]
https://jenkins.io/

**Comment by squaregoldfish** [comment]
Build and junit tests are being run as Github actions

**Comment by squaregoldfish** [comment]
I'm happy with the setup we have for the time being. Any adjustments will have their own issues.
